version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      #- echo Build started on `date`
      #- echo Building Docker test image...
      #- docker build -t $IMAGE_REPO_NAME:$TEST_IMAGE_TAG -f Dockerfile.dev .
      #- docker run -e CI=true $IMAGE_REPO_NAME:$TEST_IMAGE_TAG npm run test
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build .
      #- docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      #- docker build -t dev.datafast.io:1.0 .
      #- docker tag  dev.datafast.io:1.0 356317836475.dkr.ecr.us-east-1.amazonaws.com/dev.datafast.io:1.0
  post_build:
    commands:
      - echo Build completed on `date`
      #- echo Pushing the Docker image...
      #- docker push 356317836475.dkr.ecr.us-east-1.amazonaws.com/dev.datafast.io:1.0
      #- docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
